# Generated by Django 6.0.3 on 2026-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temperature', models.FloatField()),
                ('process_temperature', models.FloatField()),
                ('rotational_speed', models.FloatField()),
                ('torque', models.FloatField()),
                ('tool_wear', models.FloatField()),
                ('machine_failure', models.IntegerField()),
            ],
        ),
    ]
